stages:
  - clean
  - docker_build_push
  - update_manifest


variables:
  SONAR_HOST_URL: ${SONAR_HOST_URL}
  DOCKER_IMAGE_FRONTEND: "tushar8117/front-end"
  DOCKER_IMAGE_BACKEND: "tushar8117/back-end"
  MANIFEST_PATH: "k8-specification/" # Update with the relative path of your manifest file
  IMAGE_TAG: "v1"
  GITLAB_ACCESS_TOKEN: ${GITLAB_ACCESS_TOKEN}
  SONAR_TOKEN: ${SONAR_TOKEN}


clean_workspace:
  stage: clean
  script:
    - echo "Cleaning workspace"
    - rm -rf *
  

docker_build_push:
  stage: docker_build_push
  script:
    - echo "Building and pushing Docker images"
    - docker build -t tushar8117/front-end:latest ./frontend
    - docker build -t tushar8117/back-end:latest ./backend
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push tushar8117/front-end:latest
    - docker push tushar8117/back-end:latest
  

update_manifest:
  stage: update_manifest
  script:
    - git config --global user.email "ci@example.com"
    - git config --global user.name "YourGitLabUsername"
    - git remote set-url origin https://$GITLAB_ACCESS_TOKEN@gitlab.com/Tushar2003/Devops/wanderlust.git
    - sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" deployment.yml
    - git add deployment.yml
    - git commit -m "Update image tag to $IMAGE_TAG"
    - git push origin main



