stages:
  - build
  #- push

variables:
  DOCKER_DRIVER: overlay2
  

# Docker Build Stage
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t frontend_image ./frontend
  only:
    - main

# Docker Push Stage
#push:
  #stage: push
  #image: docker:latest
  #services:
    #- docker:dind
  #script:
   # - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
   # - docker tag $IMAGE_NAME $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
   # - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  #only:
#    - main