stages:
  - build
  - push
  - run
  - stop

variables:
  DOCKER_DRIVER: overlay2

# Docker Build Stage
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t frontend:latest ./frontend
    - docker build -t backend:latest ./backend
    - docker images
    - docker images > images_list.txt
  artifacts:
    paths:
      - images_list.txt 
  only:
    - main

#Docker Push Stage
push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - cat images_list.txt
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker tag frontend:latest $CI_REGISTRY/$CI_PROJECT_PATH/frontend:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  only:
    - main

run:
  stage: run
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run --name front -d -p 3000:5173 $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG

stop:
  stage: stop
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker stop front
  when: manual



