apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image:  wanderlust-frontend  # Replace with your frontend image name
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: http://backend:5000
      restartPolicy: Always
